---
# Provision sync_gateway_vms
- hosts: sg_pool

  remote_user: root
  sudo: yes

  tasks:
  - name: stop sync_gateway service
    service: name=sync_gateway state=stopped
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  - name: stop sync_gateway for CentOS 6
    shell: /sbin/initctl stop sync_gateway
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
