---
# Kill sync_gateway
- hosts: sync_gateways
  any_errors_fatal: true
  remote_user: root
  sudo: yes

  tasks:
  - include: tasks/stop-sync-gateway.yml

# Flush server buckets
- hosts: couchbase_servers
  any_errors_fatal: true
  remote_user: root
  sudo: true
  vars:
    couchbase_server_home_path: /opt/couchbase
    couchbase_server_primary_node: "{{ hostvars['cb1']['ansible_ssh_host'] }}"
    couchbase_server_admin_port: 8091
    couchbase_server_admin: Administrator
    couchbase_server_password: password
  tasks:

  - name: flush couchbase server bucket 1
    shell: "{{ couchbase_server_home_path }}/bin/couchbase-cli bucket-flush --bucket={{ item }} --force -c {{ couchbase_server_primary_node }}:{{ couchbase_server_admin_port }} --user={{ couchbase_server_admin }} --password={{ couchbase_server_password }}"
    register: bucket_flush
    with_items:
      - data-bucket
      - index-bucket
  - debug: var={{item.stdout}}
    with_items: bucket_flush.results

# Start sync_gateway
- hosts: sync_gateways
  remote_user: root
  any_errors_fatal: true
  sudo: true

  vars:
    sync_gateway_config_filepath: "files/sync_gateway_config.json"
    couchbase_server_primary_node: "{{ hostvars['cb1']['ansible_ssh_host'] }}"

  tasks:
  - include: tasks/start-sync-gateway.yml
