---
# Remove sync_gateway
- hosts: sync_gateways
  sudo: true

  tasks:

  - include: tasks/remove-sync-gateway.yml

# Flush server buckets
- hosts: couchbase_servers
  any_errors_fatal: true
  sudo: true
  vars:
    # Primary node
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].inventory_hostname }}"

    # Current node
    couchbase_server_node: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"

    couchbase_server_home_path: /opt/couchbase
    couchbase_server_admin_port: 8091
    couchbase_server_admin: Administrator
    couchbase_server_password: password

    couchbase_server_bucket_type: couchbase
    couchbase_server_bucket_port: 11211
    couchbase_server_bucket_replica: 1
    couchbase_server_cluster_ram: "{{ ((ansible_memtotal_mb|int)*0.8)|int }}"
    couchbase_server_bucket_ram: "{{ ((couchbase_server_cluster_ram|int)*0.5)|int }}"

  tasks:
  - include: tasks/flush-server-buckets.yml

# Download package and install
- hosts: sync_gateways
  any_errors_fatal: true
  sudo: true

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sync_gateway_package:
    couchbase_sync_gateway_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sync_gateway_package }}"

    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].inventory_hostname }}"

  tasks:
  # Download and extract package
  - debug: msg="Downloading sync_gateway v. {{ couchbase_sync_gateway_package_url }}"
  - name: Download sync_gateway
    get_url: url={{ couchbase_sync_gateway_package_url }} dest=/tmp/{{ couchbase_sync_gateway_package }}
  - name: Creates sync_gateway directory
    file: path=/home/centos/sync_gateway state=directory
  - name: Extract package
    unarchive: src=/tmp/{{ couchbase_sync_gateway_package }} dest=/home/centos/sync_gateway copy=no

   # Add sync_gateway user and copy binary from centos user
  - name: add sync gateway user
    user: name=sync_gateway createhome=yes
  - name: make service install script executable
    file: path=/home/centos/sync_gateway/service/sync_gateway_service_install.sh mode=a+x
  - name: copy sync gateway binary to sync_gateway home
    shell: cp /home/centos/sync_gateway/bin/sync_gateway /home/sync_gateway
  - name: change permissions of sync gateway executable
    file: path=/home/sync_gateway/sync_gateway mode=a+x

# Install and start service
- hosts: sync_gateways
  sudo: true
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].inventory_hostname }}"

  tasks:
  # Create sync_gateway user, install and start service
  - include: tasks/start-sync-gateway.yml
