---
- hosts: sync_gateways:couchbase_servers:load_generators
  any_errors_fatal: true
  tasks:

  # Remove Couchbase Server
  - include: tasks/remove-couchbase-server.yml

  # Remove sync_gateway
  - include: tasks/remove-sync-gateway.yml

  # Remove sync_gateway
  - include: tasks/remove-sg-accel.yml

  # Remove package downloads
  - name: Remove package install dir
    shell: rm -rf /tmp/*