---
# Kill sync_gateway
- hosts: sync_gateways
  any_errors_fatal: true
  sudo: yes

  tasks:
  - include: tasks/stop-sync-gateway.yml

# Deploy sync gateway configs
- hosts: sync_gateways
  sudo: true
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_ssh_host }}"
    is_index_writer: "false"
  tasks:
  - include: tasks/deploy-sync-gateway-config.yml

# Deploy sync gateway configs (index writers)
- hosts: sync_gateway_index_writers
  sudo: true
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_ssh_host }}"
    is_index_writer: "true"
  tasks:
  - include: tasks/deploy-sync-gateway-config.yml

# Start sync_gateway
- hosts: sync_gateways
  any_errors_fatal: true
  sudo: true

  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_ssh_host }}"

  tasks:
  - include: tasks/start-sync-gateway.yml
