---
- hosts: sync_gateways
  any_errors_fatal: true
  sudo: true

  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ groups.couchbase_servers[0] }}"
  tasks:
  - include: tasks/start-sync-gateway.yml