# Block http ports
- hosts: couchbase_servers
  any_errors_fatal: true
  become: yes
  tasks:
  - name: BLOCKPORTS | flush iptables before blocking
    shell: iptables -F

  - name: BLOCKPORTS | drop tcp 8091
    shell: iptables -I INPUT -p tcp --dport 8091 -j DROP

  - name: BLOCKPORTS | drop udp 8091
    shell: iptables -I INPUT -p udp --dport 8091 -j DROP

  - name: BLOCKPORTS | install iptables-services
    shell: yum -y install iptables-services

  - name: BLOCKPORTS | save iptables after dropping
    shell: service iptables save

  - name: BLOCKPORTS | restart iptables after dropping
    shell: service iptables restart
