
- name: Download Testserver C Package
  hosts: testserver
    - name: create testserver directory if not exists
    file:
        path: ~ /ctestserver
        state: directory
        when: c_testserver_dir.stat.exists == False


  tasks:
  - debug:
      msg: "testserver_download_url: {{ testserver_download_url }}"

  - debug:
      msg: "package_name: {{ package_name }}"


  - name: Download TestServer C
      get_url:
        url: "{{ testserver_download_url }}"
        dest: ~/ctestserver/{{ package_name }}.zip
      when: core_st.stat.exists == False

  - name: Unzip Couchbase Lite Library and remove .zip
      unarchive: src=~/ctestserver/{{ package_name}}.zip dest=~/ctestserver copy=no