- name: Windows - Download Testserver Java Desktop Package
  hosts: windows
  vars:
    download_url:
    package_name:
    build_name:

  tasks:
  - debug:
      msg: "download_url {{ download_url }}, build_name {{ build_name }}"

  - win_stat:
      path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\com.couchbase.TestServer.jar
    register: st

  - name: Delete any exiting packages
    win_file: 
      path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\*
      state: absent
    when: st.stat.exists == False
    ignore_errors: yes

  - debug:
      msg: "{{ build_name }} already present, skipping download..."
    when: st.stat.exists

  - name: Create TestServer directory
    win_file: 
      path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}
      state: directory
    when: st.stat.exists == False

  - name: Download TestServer Windows Java Desktop .jar
    win_get_url:
      url: "{{ download_url }}"
      dest: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ build_name }}\{{ package_name }}.jar
      skip_certificate_validation: yes
      validate_certs: no
    when: st.stat.exists == False

