- name: Windows - Start TestServer
  hosts: windows
  vars:
    binary_path:
    version_build:

  tasks:
    - win_stat:
       path: C:\Users\{{ ansible_user }}\Desktop\TestServer\TestServer-Net-C-{{ version_build }}\{{ binary_path }}
      register: st

    - debug: msg="Starting the Testserver "
    - name: Start TestServer
      win_nssm:
        name: TestServer
        application: C:\Users\{{ ansible_user }}\Desktop\TestServer\TestServer-Net-C-{{ version_build }}\{{ binary_path }}
        state: started
        stdout_file: C:\Users\{{ ansible_user }}\Desktop\TestServer\TestServer-Net-C-{{ version_build }}\TestServer.log
        stderr_file: C:\Users\{{ ansible_user }}\Desktop\TestServer\TestServer-Net-C-{{ version_build }}\TestServer.log