- name: Windows - Start TestServer
  hosts: windows
  vars:
    binary_path:
    version_build:

  tasks:
    - win_stat:
       path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ binary_path }}
      register: st

    - debug: msg="Starting the Testserver "
    - name: Start TestServer
      win_command: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ binary_path }} /c