- name: Windows - Start TestServer
  hosts: windows
  vars:
    binary_path:

  tasks:

    - debug: msg="Starting the Testserver "
    - name: Start TestServer
      win_shell: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ binary_path }}