- name: Start TestServer
  hosts: testserver
  vars:
    binary_path:

  tasks:
    - debug: msg="Starting the TestService  {{binary_path}}"
    - name: Start TestServer
      command: "nohup  ~/ctestserver/testserver &"
      ignore_errors: yes
