- name: Windows - Start TestServer
  hosts: windows
  vars:
    binary_path:

  tasks:
    - win_stat:
       path: C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ binary_path }}
      register: st

    - debug: msg="Starting the Testserver "
    - name: Start TestServer
      win_command: C:\PROGRA~1\dotnet\dotnet C:\Users\{{ ansible_user }}\Desktop\TestServer\{{ binary_path }}
      when: st.stat.exists == True