
- name: Start TestServer
  hosts: testserver
  vars:
    binary_path:

  tasks:
    - debug: msg="Starting the TestService  {{binary_path}}"
    - name: Start TestServer
      shell: "nohup /Users/couchbase/ctestserver/testserver &"
      args:
        chdir: "/Users/couchbase/ctestserver"
