- name: Start TestServer
  hosts: testserver
  vars:
    binary_path:

  tasks:
    - debug: msg="Starting the TestService  {{binary_path}}"
    - name: Start TestServer
      shell: "/root/ctestserver/testserver &"
      args:
        chdir: "/root/ctestserver"
        executable: "/bin/bash"
