- name: Start TestServer
  hosts: testserver
  vars:
    binary_path:

  tasks:
    - debug: msg="Starting the TestService  {{binary_path}}"
    - name: Start TestServer
      command: "start-stop-daemon --start --quiet --exec /root/ctestserver/testserver --background"




