- name: Stop Couchbase Service
  service: name=couchbase-server state=stopped
  ignore_errors: yes

# Try to stop via init scipt if running CBS 4.1.0 on CentOS 7.2 due to https://issues.couchbase.com/browse/MB-17193
- name: Try to stop Couchbase Service (Hack around 7.2 and CBS 4.1.0 issue)
  shell: /opt/couchbase/etc/couchbase_init.d stop
  when: ansible_distribution == 'CentOS' and ansible_distribution_version == '7.2.1511'
  ignore_errors: yes

- name: Uninstall couchbase server
  shell: rpm -e couchbase-server
  ignore_errors: yes

# Kill any processes that may be hanging around
- name: Kill epmd
  shell: pkill epmd
  ignore_errors: yes

- name: Kill beam.smp
  shell: pkill beam.smp
  ignore_errors: yes

- name: Kill memcached
  shell: pkill memcached
  ignore_errors: yes

- name: Remove all couchbase server residue
  file: path=/opt/couchbase state=absent
