# Stop sync_gateway service
- name: stop sg_accel service
  service: name=sg_accel state=stopped
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  ignore_errors: yes

- name: stop sg_accel for CentOS 6
  shell: /sbin/initctl stop sg_accel
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  ignore_errors: yes

- name: verify sg_accel not listening on port
  wait_for: port=4985 delay=1 state=stopped

# Remove sg_accel package
- name: Uninstall sync_gateway rpm
  shell: rpm -e couchbase-sg-accel
  ignore_errors: yes

# Remove sg_accel service
- name: Remove sg_accel service
  shell: rm /usr/lib/systemd/system/sg_accel.service
  ignore_errors: yes

# Delete sg_accel binary
- name: delete sync_gateway binary
  shell: rm -rf /opt/couchbase-sg-accel

# Delete logs and .pindex files
- name: delete sg_accel logs
  shell: rm -f /home/sg_accel/logs/*.log
- name: delete sg_accel pindex files
  shell: rm -rf /home/sg_accel/*.pindex

# Remove sync_gateway user
- name: remove sg accel user
  user: name=sg_accel state=absent remove=yes force=yes
  ignore_errors: yes

# Delete downloaded source
- name: delete previous sync gateway
  command: rm -rf /home/centos/sync_gateway